In [32]:
import pandas as pd

In [33]:
pd.__version__

'2.2.2'

In [34]:
df = pd.read_csv('yellow_tripdata_2021-01.csv.gz', nrows=100)

In [35]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2,2021-01-01 00:12:41,2021-01-01 00:26:47,1,4.13,1,N,161,226,1,14.5,0.5,0.5,3.66,0.0,0.3,21.96,2.5
96,2,2021-01-01 00:23:29,2021-01-01 00:35:03,2,4.12,1,N,162,74,2,13.5,0.5,0.5,0.00,0.0,0.3,17.30,2.5
97,2,2021-01-01 00:46:17,2021-01-01 00:54:25,2,2.22,1,N,144,170,1,9.0,0.5,0.5,2.56,0.0,0.3,15.36,2.5
98,2,2021-01-01 00:28:16,2021-01-01 00:51:44,1,7.11,1,N,264,264,2,23.5,0.5,0.5,0.00,0.0,0.3,24.80,0.0
99,2,2021-01-01 00:42:35,2021-01-01 00:54:41,3,1.61,1,N,229,237,2,9.5,0.5,0.5,0.00,0.0,0.3,13.30,2.5

In [36]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data'))

CREATE TABLE "yellow_taxi_data" (
"VendorID" INTEGER,
  "tpep_pickup_datetime" TEXT,
  "tpep_dropoff_datetime" TEXT,
  "passenger_count" INTEGER,
  "trip_distance" REAL,
  "RatecodeID" INTEGER,
  "store_and_fwd_flag" TEXT,
  "PULocationID" INTEGER,
  "DOLocationID" INTEGER,
  "payment_type" INTEGER,
  "fare_amount" REAL,
  "extra" REAL,
  "mta_tax" REAL,
  "tip_amount" REAL,
  "tolls_amount" REAL,
  "improvement_surcharge" REAL,
  "total_amount" REAL,
  "congestion_surcharge" REAL
)

^ This is called DDL (data definition language) which describes the schema and table should look like in SQL
tpep_pickup_datetime and tpep_dropoff_datetime have the wrong data type.

In [37]:
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

Notice how these 2 fields got changed to timestamp from text

In [38]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data'))

CREATE TABLE "yellow_taxi_data" (
"VendorID" INTEGER,
  "tpep_pickup_datetime" TIMESTAMP,
  "tpep_dropoff_datetime" TIMESTAMP,
  "passenger_count" INTEGER,
  "trip_distance" REAL,
  "RatecodeID" INTEGER,
  "store_and_fwd_flag" TEXT,
  "PULocationID" INTEGER,
  "DOLocationID" INTEGER,
  "payment_type" INTEGER,
  "fare_amount" REAL,
  "extra" REAL,
  "mta_tax" REAL,
  "tip_amount" REAL,
  "tolls_amount" REAL,
  "improvement_surcharge" REAL,
  "total_amount" REAL,
  "congestion_surcharge" REAL
)

In [39]:
from sqlalchemy import create_engine

Connect to the Postgres DB that we initiated

In [40]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')
engine.connect()

postgresql://root:root@localhost:5432/ny_taxi
postgresql - type of DB
root - user
root - password
localhost - hostname
5432 - port
ny_taxi - DB name

In [41]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))
# con=engine → Uses the SQLAlchemy engine (engine) to infer the correct data types based on PostgreSQL. 
#If you don't specify the con parameter in get_schema(), Pandas will default to SQLite for generating the CREATE TABLE statement.

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [42]:
df_iter = pd.read_csv('yellow_tripdata_2021-01.csv.gz', iterator=True, chunksize=100000)

In [43]:
df = next(df_iter) #returns the next element in the iterator

In [44]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,2021-01-04 14:04:31,2021-01-04 14:08:52,3,0.70,1,N,234,224,2,5.0,2.5,0.5,0.00,0.0,0.3,8.30,2.5
99996,1,2021-01-04 14:18:46,2021-01-04 14:35:45,2,3.30,1,N,234,236,1,14.5,2.5,0.5,3.55,0.0,0.3,21.35,2.5
99997,1,2021-01-04 14:42:41,2021-01-04 14:59:22,2,4.70,1,N,236,79,1,17.0,2.5,0.5,4.05,0.0,0.3,24.35,2.5
99998,2,2021-01-04 14:39:02,2021-01-04 15:09:37,2,17.95,2,N,132,148,1,52.0,0.0,0.5,5.00,0.0,0.3,60.30,2.5
99999,2,2021-01-04 14:49:36,2021-01-04 14:54:44,5,0.37,1,N,236,236,2,5.0,0.0,0.5,0.00,0.0,0.3,8.30,2.5

In [45]:
len(df)

100000

In [46]:
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

In [47]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,2021-01-04 14:04:31,2021-01-04 14:08:52,3,0.70,1,N,234,224,2,5.0,2.5,0.5,0.00,0.0,0.3,8.30,2.5
99996,1,2021-01-04 14:18:46,2021-01-04 14:35:45,2,3.30,1,N,234,236,1,14.5,2.5,0.5,3.55,0.0,0.3,21.35,2.5
99997,1,2021-01-04 14:42:41,2021-01-04 14:59:22,2,4.70,1,N,236,79,1,17.0,2.5,0.5,4.05,0.0,0.3,24.35,2.5
99998,2,2021-01-04 14:39:02,2021-01-04 15:09:37,2,17.95,2,N,132,148,1,52.0,0.0,0.5,5.00,0.0,0.3,60.30,2.5
99999,2,2021-01-04 14:49:36,2021-01-04 14:54:44,5,0.37,1,N,236,236,2,5.0,0.0,0.5,0.00,0.0,0.3,8.30,2.5

In [48]:
df.head(n=0)

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge]
Index: []

In [49]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')
#creates or replaces the table structure in PostgreSQL without inserting any data

0

In [50]:
%time df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

CPU times: user 7.71 s, sys: 101 ms, total: 7.82 s
Wall time: 13.8 s

1000

In [51]:
from time import time

In [52]:
while True: 
    try:
        t_start = time()
        
        df = next(df_iter)
        df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
        df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)
        
        df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')
        
        t_end = time()
        print('insert another chunk..., took %.3f seconds' % (t_end - t_start))
    except StopIteration:
        print('End of file reached. Stopping interaction') 
        break

insert another chunk..., took 14.090 seconds
insert another chunk..., took 14.009 seconds
insert another chunk..., took 13.923 seconds
insert another chunk..., took 13.916 seconds
insert another chunk..., took 13.791 seconds
insert another chunk..., took 13.978 seconds
insert another chunk..., took 14.000 seconds
insert another chunk..., took 13.912 seconds
insert another chunk..., took 13.819 seconds
insert another chunk..., took 14.030 seconds
insert another chunk..., took 13.943 seconds

/tmp/ipykernel_64220/3656429133.py:5: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = next(df_iter)

insert another chunk..., took 13.969 seconds
insert another chunk..., took 8.841 seconds
End of file reached. Stopping interaction

In [54]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
1300000,NaN,2021-01-05 10:38:40,2021-01-05 10:46:20,NaN,1.30,NaN,NaN,170,161,NaN,7.00,0.00,0.5,1.03,0.00,0.3,11.33,2.5
1300001,NaN,2021-01-05 10:17:14,2021-01-05 10:41:21,NaN,7.90,NaN,NaN,216,198,NaN,31.49,0.00,0.5,2.75,0.00,0.3,35.04,0.0
1300002,NaN,2021-01-05 10:39:00,2021-01-05 10:46:00,NaN,0.98,NaN,NaN,62,62,NaN,16.23,0.00,0.5,2.75,0.00,0.3,19.78,0.0
1300003,NaN,2021-01-05 10:05:00,2021-01-05 10:19:00,NaN,1.59,NaN,NaN,85,71,NaN,13.45,0.00,0.5,2.75,0.00,0.3,17.00,0.0
1300004,NaN,2021-01-05 10:18:08,2021-01-05 10:41:40,NaN,9.87,NaN,NaN,236,208,NaN,30.23,0.00,0.5,2.75,6.12,0.3,39.90,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369760,NaN,2021-01-25 08:32:04,2021-01-25 08:49:32,NaN,8.80,NaN,NaN,135,82,NaN,21.84,2.75,0.5,0.00,0.00,0.3,25.39,0.0
1369761,NaN,2021-01-25 08:34:00,2021-01-25 09:04:00,NaN,5.86,NaN,NaN,42,161,NaN,26.67,2.75,0.5,0.00,0.00,0.3,30.22,0.0
1369762,NaN,2021-01-25 08:37:00,2021-01-25 08:53:00,NaN,4.45,NaN,NaN,14,106,NaN,25.29,2.75,0.5,0.00,0.00,0.3,28.84,0.0
1369763,NaN,2021-01-25 08:28:00,2021-01-25 08:50:00,NaN,10.04,NaN,NaN,175,216,NaN,28.24,2.75,0.5,0.00,0.00,0.3,31.79,0.0
1369764,NaN,2021-01-25 08:38:00,2021-01-25 08:50:00,NaN,4.93,NaN,NaN,248,168,NaN,20.76,2.75,0.5,0.00,0.00,0.3,24.31,0.0

In [61]:
print(df.iloc[:, 6].apply(type).value_counts())

store_and_fwd_flag
<class 'str'>    100000
Name: count, dtype: int64

In [69]:
df = pd.read_csv('yellow_tripdata_2021-01.csv.gz', nrows=100)
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [70]:
df_iter = pd.read_csv(
    'yellow_tripdata_2021-01.csv.gz',
    iterator=True,
    chunksize=100000,
    dtype={"store_and_fwd_flag": str},  # Force column as string
    low_memory=False  # Avoid chunk-based type guessing
)

while True: 
    try:
        t_start = time()
        
        df = next(df_iter)
        df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
        df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)
        df["store_and_fwd_flag"] = df["store_and_fwd_flag"].astype(str)
        
        df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')
        
        t_end = time()
        print('insert another chunk..., took %.3f seconds' % (t_end - t_start))
    except StopIteration:
        print('End of file reached. Stopping interaction') 
        break

insert another chunk..., took 26.648 seconds
insert another chunk..., took 19.863 seconds
insert another chunk..., took 14.862 seconds
insert another chunk..., took 14.711 seconds
insert another chunk..., took 14.648 seconds
insert another chunk..., took 14.777 seconds
insert another chunk..., took 14.694 seconds
insert another chunk..., took 14.830 seconds
insert another chunk..., took 14.696 seconds
insert another chunk..., took 14.605 seconds
insert another chunk..., took 15.093 seconds
insert another chunk..., took 14.755 seconds
insert another chunk..., took 14.235 seconds
insert another chunk..., took 9.697 seconds
End of file reached. Stopping interaction

Alternative way to access the DB if pgcli does not work:

In [64]:
df = pd.read_csv('yellow_tripdata_2021-01.csv.gz', nrows=100, dtype={"store_and_fwd_flag": str})
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

In [65]:
df.to_sql(name='yellow_taxi_data_2', con=engine, index=False)

100

In [67]:
query = """
SELECT * FROM yellow_taxi_data_2 LIMIT 10
"""

pd.read_sql(query, con=engine)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5
5,1,2021-01-01 00:16:29,2021-01-01 00:24:30,1,1.60,1,N,224,68,1,8.0,3.0,0.5,2.35,0.0,0.3,14.15,2.5
6,1,2021-01-01 00:00:28,2021-01-01 00:17:28,1,4.10,1,N,95,157,2,16.0,0.5,0.5,0.00,0.0,0.3,17.30,0.0
7,1,2021-01-01 00:12:29,2021-01-01 00:30:34,1,5.70,1,N,90,40,2,18.0,3.0,0.5,0.00,0.0,0.3,21.80,2.5
8,1,2021-01-01 00:39:16,2021-01-01 01:00:13,1,9.10,1,N,97,129,4,27.5,0.5,0.5,0.00,0.0,0.3,28.80,0.0
9,1,2021-01-01 00:26:12,2021-01-01 00:39:46,2,2.70,1,N,263,142,1,12.0,3.0,0.5,3.15,0.0,0.3,18.95,2.5